// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwYSNToNd9JQVY4LMQo_XpcMBCIZkaSYc',
    appId: '1:332596907910:web:03098b99736f426f936607',
    messagingSenderId: '332596907910',
    projectId: 'mula-becb6',
    authDomain: 'mula-becb6.firebaseapp.com',
    storageBucket: 'mula-becb6.firebasestorage.app',
    measurementId: 'G-5RW1H5HX51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjIu4imHBtCylrqthdcedGQHyro35L28',
    appId: '1:332596907910:android:589348de4064be06936607',
    messagingSenderId: '332596907910',
    projectId: 'mula-becb6',
    storageBucket: 'mula-becb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCghoLQDAuhIKwuBbuUQRVi1mBBJAf5AJc',
    appId: '1:332596907910:ios:f50d7f915cdcd2d1936607',
    messagingSenderId: '332596907910',
    projectId: 'mula-becb6',
    storageBucket: 'mula-becb6.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCghoLQDAuhIKwuBbuUQRVi1mBBJAf5AJc',
    appId: '1:332596907910:ios:f50d7f915cdcd2d1936607',
    messagingSenderId: '332596907910',
    projectId: 'mula-becb6',
    storageBucket: 'mula-becb6.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwYSNToNd9JQVY4LMQo_XpcMBCIZkaSYc',
    appId: '1:332596907910:web:ccd7c15a13696151936607',
    messagingSenderId: '332596907910',
    projectId: 'mula-becb6',
    authDomain: 'mula-becb6.firebaseapp.com',
    storageBucket: 'mula-becb6.firebasestorage.app',
    measurementId: 'G-K15HYFX6GW',
  );
}
